language: go

go:
        #  - 1.3
        #  - 1.4.2
  - 1.5.1

os:
        #  - linux
  - osx

before_install:
        # - sudo apt-get update -q -y
        # - sudo apt-get install libnetcdf-dev -y
  - brew tap homebrew/science
  - brew update
  - brew install  netcdf

script:
  - go install -v ./...
  - go test -v ./...
  - oceano2oceansites -e --files=data/csp/csp*.cnv
