language: go

go:
        #  - 1.3
        #  - 1.4.2
  - 1.5.1

os:
  - linux
  - osx

before_install:
  # Install Linux netcdf
  - |
    if test "${TRAVIS_OS_NAME}" == "linux"; then
        sudo apt-get update -q -y
        sudo apt-get install libnetcdf-dev -y
    fi 
  # Install OS X netcdf
  - |
    if test "$TRAVIS_OS_NAME" == "osx"; then
        brew tap homebrew/science
        #brew update
        brew install netcdf
    fi

script:
  - go install -v ./...
  - go test -v ./...
  - oceano2oceansites -e --files=data/csp/csp*.cnv
